combikubecourse:
  rabbitmq:
    url: "rabbitmq.messagebroker.svc.cluster.local"
    port: "5672"
    vhost: "demo"
    queue: "argo-example"
    exchange: "signal"
    auth:
      existingSecret: "rabbitmq-credentials"

  deployments:
    producer:
      replicaCount: 1
      image:
        repository: "combikubecourse.azurecr.io/demo/producer"
        tag: "1"
      extraEnvVars:
        - name: SIGNAL_TYPE
          value: "square"
        - name: RABBITMQ_VHOST
          value: "demo"
    consumer:
      replicaCount: 1
      image:
        repository: "combikubecourse.azurecr.io/demo/consumer"
        tag: "1"
      extraEnvVars:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: CONFIG_PATH
          value: "/config"        
      volumes:
        - name: config
          configMap:
            name: conf

      # Additional volumeMounts on the output Deployment definition.
      volumeMounts:
        - name: config
          mountPath: /config
