{{- range $name, $spec := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "combikubecourse.fullname" $ }}-{{ $name }}
  labels:
    {{- include "combikubecourse.labels" $ | nindent 4 }}
spec:
  revisionHistoryLimit: 0
{{- with $spec }}
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "combikubecourse.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "combikubecourse.labels" $ | nindent 8 }}
      annotations:
        checksum/config-files: {{ tpl (($.Files.Glob "conf/*").AsConfig) $ | sha256sum }}
        checksum/config-secret: {{ include (print $.Template.BasePath "/secret-rabbitmq.yaml") $ | sha256sum }}

        checksum/config-envs: {{ include (print $.Template.BasePath "/configmap-common-envs.yaml") $ | sha256sum }}
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "combikubecourse.serviceAccountName" $ }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          env:
            {{- with .extraEnvVars -}}
            {{ . | toYaml | nindent 12}}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-env-vars" (include "combikubecourse.fullname" $) }}
            - secretRef:
                name: {{ empty $.Values.rabbitmq.auth.existingSecret | ternary (printf "%s-env-vars" (include "combikubecourse.fullname" $)) ($.Values.rabbitmq.auth.existingSecret) }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
---
{{- end }}
